In [28]:
import numpy as np
import JG_Helpers as jg

print("Hello World")

print(jg.test_implementation())

y_in = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
b = [-1,-1,-1]

#weigths = np.random.uniform(low=-1, high=1, size=(3, 3))
#z = np.dot(y_in, weigths)
#print(z.shape, ":: without b")
#print(b.shape)

z = np.array(y_in) + b
print(z)
print(z.shape)

Hello World
JG_Helpers Was Imported Properly
None
[[0 0 0]
 [1 1 1]
 [2 2 2]]
(3, 3)
